package enums;

public enum PrimaryStat implements Stat {
	STRENGTH, DEXTERITY, CONSTITUTION, INTELLIGENCE, WISDOM, CHARISMA, ARMOR_CLASS, CURRENT_HEALTH, INITIATIVE, MAX_HEALTH, SPEED, TEMPORARY_HEALTH, PROFICIENCY
}
